### PR TITLE
chore: avoid checklist on issues

### PR DESCRIPTION
**Pull request by caroso1222**
The current issue template creates a checklist-type issue which is a bit misleading given that the issue itself is not representing a checklist but rather a user selection. Having the checklist rendered as a code snippet will avoid this. PD: the proposed fix is emoji compatible.

### CODE REVIEW

**Review by jdjuan — CHANGES_REQUESTED** [review]
Same comment as of Angular Medellín. What do you think?

**Comment by caroso1222** [comment]
It all depends on what you're trying to achieve. My PR is based on keeping the issue form consistent with those from angular and angular-cli. Both of them render the user selection as code snippets given that a checkbox list is a whole different use case. See examples below:

angular/angular#17578
angular/angular-cli#6723

**Comment by jdjuan** [comment]
So I already answered in @Angular-medellin, but here we don't need to stick to those principles. If you haven't changed your mind then we can proceed with this PR. ¿What do you think? 👍

**Comment by jdjuan** [comment]
@caroso1222 did you 👀 my comment ⏫ ⏫ ⏫  🤣

**Comment by caroso1222** [comment]
Thanks. I will proceed to merge the PR then.

**Pull request merged**
