### PR TITLE
build: add contributing guidelines

### PR DESCRIPTION
**Pull request by jdjuan**
@caroso1222 I added the website to the repository so people can more easily develop over ng-notyf 😁

### CODE REVIEW

**Comment by jdjuan** [comment]
Have you reviewed this @caroso1222 ! 😀

**Comment by caroso1222** [comment]
hey @jdjuan! seems like it's been a while with this PR opened :P sorry about that! PR looks great, I'll approve, feel free to merge please.

**Review by caroso1222 — APPROVED** [review]
LGTM

**Comment by jdjuan** [comment]
And it only took you 8 months 😏

**Pull request merged**
